name: Art job
# This workflow is triggered on pushes to the repository.
on: 
#  push:
#    path:
      # We are saving the cool results here, lets prevent this action to trigger if something is added here. Otherwise this will run forever
#      - '!art/**'
  schedule:
    - cron:  "53 10 * * 5" #build project on the 15th day of every month on the 42nd minute of the 7th hour.
  workflow_dispatch:

jobs:
  build:
    name: Do art
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "$(date)"
      # This is to clone the current repo
      - uses: actions/checkout@v3
        with:
          path: 'target4art'
      - run: |
          # Save the current dir for latter commit
          CURRENT_DIR="$GITHUB_WORKSPACE/target4art"
          echo $CURRENT_DIR
          # The previous step clones this repo, just go out of the folder to not mess up two repos in the same place
          cd /
          sudo git clone https://github.com/bbaudry/gen-art-action.git gen-art-folder
          sudo chown $USER:$USER gen-art-folder
          cd gen-art-folder
          bash ./cool-genart.sh
          # COPY the cool result to this repo folder
          sudo mkdir -p $CURRENT_DIR/art/
          sudo cp friday.art $CURRENT_DIR/art/friday-$RANDOM-$(date+'%Y-%m-%d').art
          cd $CURRENT_DIR
          
          # Then commit the new art
          git config --global user.email "almyre@gmail.com"
          git config --global user.name "almyre"
          git add art/
          git commit -m "New art added"
          sudo git push --force